### ISSUE TITLE
Change UI and UICategory to opaque types

### ISSUE THREAD

**Issue by FabienHenon** [kalutheo/elm-ui-explorer#13]
In order to avoid major version bumps when changing the model (even for not breaking changes), you should turn your exposed types to opaque types.

Here is the way to do it (for `UI`):

```elm
type UI
    = UIType InternalUI

type alias InternalUI =
    { id : String
    , description : String
    , viewStories : UIViewConfig -> Html Msg
    }
```

When a function needs a `UI` as parameter just do like this:

```elm
funcWithUI : UI -> String
funcWithUI (UIType ui) =
    ui.description
```

You don't have to change your current exposes (you have to expose `UI` and not `UI(..)`, otherwise the type is not opaque anymore as anyone using the module can create a `UI` object like this: `UIType {.....}`

But you will have to create helper functions to create these opaque objects. Try to keep these functions small and atomic so that any change in the model won't force you to rewrite these helper functions. This way you won't have breaking changes, only new features ;)

Example for `UI` type, assuming a description is optional and defaults to empty string (you should turn it to a `Maybe` then, but let's assume it is a simple `String` for the example):

```elm
newUI : String -> (UIViewConfig> Html Msg) -> UI
newUI id viewStories =
    UIType {id = id, description = "", viewStories = viewStories}

withDescription : String -> UI -> UI
withDescription description (UIType ui) =
    UIType { ui | description = description }
```

Don't forget to expose these functions and to write a documentation for them ;)
And don't forget to separate your documentation in categories:

```elm
module UIExplorer exposing (app, renderStories, UI, UICategory, newUI, withDescription)

{-|
Component Explorers and Style Guides have been around for a while now.
We don't build pages anymore but components that are assembled together to build Systems.
In the ELM world, components are just called views, and are defined as pure functions.
ELM UI Explorer takes advantage of the composability and the purity of ELM and offers a way to showcase
your views and their states in a single tool.
Inspired by [React Storybook](https://storybook.js.org/)

# UIExplorer
@docs app, renderStories

# Models
@docs UI, UICategory

# UI Helpers
@docs newUI, withDescription
-}
```

**Comment by kalutheo** [comment]
@FabienHenon Thanks very much for your advices !

**Comment by kalutheo** [comment]
I have started to add OpaqueType on `UICategory` on `opaque-type` branch.
But i have the following error ...

<img width="804" alt="capture d ecran 2017-10-07 a 10 30 58" src="https://user-images.githubusercontent.com/15056358/31306176-a998e7ba-ab4a-11e7-8e20-2fe32713bd0d.png">

**Comment by FabienHenon** [comment]
`Tuple.second` on line `337` is expecting the type to be a `Tuple`, but now `model.categories` is not a `List (a, b)` but a `List t` because `UICategory` is not a `Tuple` anymore but a `type` with one value `UICategoryType`

Thus, your code should be something like this:

```elm
model.categories
    |> List.map getTupleSecondFromCategory
```

And `getTupleSecondFromCategory` should be: 

```elm
getTupleSecondFromCategory : UICategory -> List UI
getTupleSecondFromCategory (UICategoryType (n, uiList) =
    uiList
```

I guess you can also declare this function directly in your `viewContent` function in the `let` block:

```elm
-- ...
let
    getTupleSecondFromCategory (UICategoryType (n, uiList) =
        uiList

    filteredUIs =
        model.categories
            |> List.map getTupleSecondFromCategory
            |> List.foldr (++) []
            |> List.filter (\ui -> filterSelectedUI ui model)

    -- ...
in
    -- ...
```

**Comment by kalutheo** [comment]
@FabienHenon great ! i manage to make my types opaque. Here is the pull request  #15
