### ISSUE TITLE
Less invasive CSS framework? 

### ISSUE THREAD

**Issue by justgage** [kalutheo/elm-ui-explorer#16]
Bluma is cool however I find that it pollutes the namespace if you are using something else. Meaning it effects the buttons and other primative HTML tags so that they'll look different than they would outside of the UI-explorer. 

I think some alternative would be:
- Tachyons, it doesn't effect the HTML primitives much and it would be quick for me to switch it over if you want. 
- Inline CSS. This is good because it doesn't bleed out probably.
- Styled elements, Elm CSS, raw CSS: just write a custom theme which is more effort but as long as you namespace your CSS classes well it shouldn't affect the internals

**Comment by justgage** [comment]
Also something with an iframe or Shadow Dom might be an option, I think these might require a build step but I'm not sure

**Comment by kalutheo** [comment]
Hi there ! totally agree with you. i was thinking of using [tailwindcss](https://tailwindcss.com/).
It's an utility-first CSS framework like Tachyons . It's true that Bulma is a good framework but can be intrusive 

Feel free if you want to collaborate and open a PR on the subject.

**Comment by kalutheo** [comment]
i'am not a fan of iframes ,  it can be hard to work with .... i remember some headaches when working with them 😀  .  And Shadow Dom i have not experience with that. How would you handle that with it ?

**Comment by justgage** [comment]
Yeah I hate I-frames. I don't know much about the shadow dom either so 🤷‍♂️ . 

Tailwind looks sweet! Previous to you suggesting that I started converting things over to use Tachyons on my fork: https://github.com/justgage/elm-ui-explorer However it would be relatively simple to translate those classes to tailwind. It might even be a good idea to use some css fancyness (some postcss plugin?) to prefix all the classes so we don't conflict with other people's class names.

**Comment by theocar** [comment]
Hi @justgage i ran your fork. That's cool, i see the idea  :-)
I will work on a Tailwind branch and take advantage of that to redo the design of the UIExplorer . 
Tailwindcss comes with css prefixing out of the box. So i will implement it too.
Thanks for your help . Will let you know when i have finished  😎

**Comment by justgage** [comment]
Sounds awesome! I'm excited to see how it turns out! Sorry I haven't had
much time to collaborate.

**Comment by anagrius** [comment]
@theocar Have you considered the css property `contain: strict`?
Not sure it would work but it might be worth a try.
https://developer.mozilla.org/en-US/docs/Web/CSS/contain

**Comment by kalutheo** [comment]
I added tailwindcss in the last release
