### ISSUE TITLE
Replace css cdn to the new one in examples

### ISSUE THREAD

**Issue by Denisiums** [kalutheo/elm-ui-explorer#18]
For examples in exaplorer's index.html
`https://rawgit.com/kalutheo/elm-ui-explorer/tailwindcss/assets/styles.css`
returns 404.
The right one is
`https://cdn.rawgit.com/kalutheo/elm-ui-explorer/master/assets/styles.css`

**Comment by kalutheo** [comment]
Thanks for the feedback will fix that

**Comment by kalutheo** [comment]
@Denisiums fixed by https://github.com/kalutheo/elm-ui-explorer/pull/19
