### ISSUE TITLE
UIExplorer not exposing types

### ISSUE THREAD

**Issue by shahankit** [kalutheo/elm-ui-explorer#20]
When I try to write the following code
```elm
viewStories : UIExplorer.UIViewConfig -> Html.Html UIExplorer.Msg
viewStories =
    renderStories render stories
```

The compiler throws an error saying `UIExplorer` does not expose `Msg`. Is there a way to write type annotation for this case?

**Comment by lisardo** [comment]
I created a PR for this issue:
https://github.com/kalutheo/elm-ui-explorer/pull/21

**Comment by kalutheo** [comment]
Hello @shahankit, @lisardo  1.1.0 fixes the issue
