### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by jakubea** [kalutheo/elm-ui-explorer#24]
We use this package for our project and I was wondering if there's any time estimation when it will be ready to be used with Elm 0.19?

**Comment by kalutheo** [comment]
Hi @jakubea ! Happy to see that you are using the package :-)
The Upgrade to Elm 0.19 is in progress. I'am taking advantage of this upgrade to simplify the API and add new features. I'am planning to release the next version next month

**Comment by kalutheo** [comment]
Hi @jakubea the library has been upgraded to Elm 0.19
https://github.com/kalutheo/elm-ui-explorer/releases/tag/2.0.0

Feel free to ask questions if issue with the migration
