### ISSUE TITLE
Maybe allow spaces in storiesOf

### ISSUE THREAD

**Issue by sporto** [kalutheo/elm-ui-explorer#27]
If I add a space into `storiesOf` the navigation will be broken e.g.

```
storiesOf "Checkout Widget"
```

Same for the labels in the tuple

```
[  ( "Not loaded", \_ -> GreatUI.viewLoading, {} )
```

Would be great if this could handle labels with spaces and not just ids.
Thanks

**Comment by kalutheo** [comment]
Hey @sporto for sure ! PR are welcome if you have some time .
Anyway i will add it to the next milestone

**Comment by kalutheo** [comment]
Fixed in the latest version https://github.com/kalutheo/elm-ui-explorer/releases/tag/2.0.3
