### ISSUE TITLE
Changing NoOp to ExternalMsg allows for having interactive stories.

### ISSUE THREAD

**Issue by francescortiz** [kalutheo/elm-ui-explorer#28]
I've been using elm-ui-explorer to implement an app using atomic design principle. It was perfect until I wanted to test basic interactivity. By default all Html messages are mapped to NoOp. It is surprising because simply by wrapping them with ExternalMsg interaction works honoring the update function defined in the config.

Do you think it is ok to have `Html.map ExternalMsg` instead of `(\_ -> NoOp)`?

**Comment by kalutheo** [comment]
Hey @francescortiz this is a great idea :-D 
I will add that in the next version stay tuned :-)

**Comment by francescortiz** [comment]
Awesome! Thank you!

**Comment by kalutheo** [comment]
Fixed in the latest version https://github.com/kalutheo/elm-ui-explorer/releases/tag/2.0.3

**Comment by francescortiz** [comment]
Works perfectly. Thanks!
