### ISSUE TITLE
Customize the logo

### ISSUE THREAD

**Issue by jouderianjr** [kalutheo/elm-ui-explorer#32]
I'm setting the UI Explorer to use it internally and I was trying to customize the logo, but the type only accepts string, what do you be able to pass an `Html msg` also? This way I could customize the way I want.

If you agree with the idea I could create a PR :)

**Comment by kalutheo** [comment]
Hello ! Happy to see that you are using it internally :)
Just do a MR I will review it with pleasure. Do not hesitate ;)  it’s a very good idea

**Comment by jouderianjr** [comment]
Cool! I will give a shot this week :D

**Comment by kalutheo** [comment]
published in v 3.0.0 thanks :-)
