### ISSUE TITLE
Overflow set to hidden in storybook demo

### ISSUE THREAD

**Issue by supermacro** [kalutheo/elm-ui-explorer#41]
When navigating to https://kalutheo.github.io/elm-ui-explorer/examples/dsm/index.html#Styles/Typography/Typography

I noticed that a lot of the content is not visible as it goes beyond the viewport.

**Comment by kalutheo** [comment]
hey fixed in latest version : https://elm-ui-explorer.netlify.app/examples/dsm/#Styles/Typography/Typography
