### ISSUE TITLE
Disable color mode button

### ISSUE THREAD

**Issue by jouderianjr** [kalutheo/elm-ui-explorer#53]
The current design I'm working on doesn't have any dark mode support. Do you think it makes sense be able do remove the button from the header?

I'm glad to do the PR if you agree.

**Comment by kalutheo** [comment]
Hey in fact we can imagine making it optional 
PR are more than welcome 😀

**Comment by kalutheo** [comment]
Hello,
The Dark Mode button can now be enabled/disabled in the last version 
https://github.com/kalutheo/elm-ui-explorer/releases/tag/9.0.0

Example here : 
https://github.com/kalutheo/elm-ui-explorer/blob/master/examples/button/ExplorerWithFlags.elm#L19
