### ISSUE TITLE
Knobs plugin not available in elm packages

### ISSUE THREAD

**Issue by lemol** [kalutheo/elm-ui-explorer#55]
Knobs plugin not available in elm packages although it has an example in the README.

Is this a bug?

**Comment by kalutheo** [comment]
Hey true it’s not normal I forgot to expose it 😀but it’s ready . Will fix that

**Comment by kalutheo** [comment]
Hey ! Knobs are now available in the docs : https://package.elm-lang.org/packages/kalutheo/elm-ui-explorer/latest/UIExplorer-Plugins-Knobs
Sorry again for that 🙏
