### ISSUE TITLE
Unable to run `npm run uie` successfully

### ISSUE THREAD

**Issue by anirudh-janga** [kalutheo/elm-ui-explorer#60]
It looks like the elm package manager is trying to find a specific package that is missing.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/7342625/93716427-68e68e00-fb35-11ea-971e-4a629ffc209e.png">

**Comment by kalutheo** [comment]
Hey 👋🏿 in fact this is a problem that started last weeke apparently this package has been renamed and moved elsewhere. I am going to fix that and will let you know about the fix . Thanks

**Comment by anirudh-janga** [comment]
Thank you!

**Comment by kalutheo** [comment]
It should be fine now if you install the latest version of `uie cli`
;)
