### ISSUE TITLE
Flags?

### ISSUE THREAD

**Issue by sporto** [kalutheo/elm-ui-explorer#67]
Hi

We are trying this and seems really nice. However we pass some information to the app via flags (e.g. paths for assets).
It doesn't appear there is a way to pass flags, at least not with `explore`. 
Is it possible, any examples?

Thanks

**Comment by kalutheo** [comment]
Hello,
Great to hear that. for now there's no compatibility with Flags.
In fact we could imagine providing the title, logo, bgColor etc... via a Flags :) 
i did not think about that. I am going to add it to the next release. I am planning to ship a new version end of march
i will let you know. if you have other ideas or blockers let me know :)

**Comment by kalutheo** [comment]
Hello, 
The latest version provides a way to feed the explorer with Flags 
https://github.com/kalutheo/elm-ui-explorer/releases/tag/9.0.0

An example can be found here : https://github.com/kalutheo/elm-ui-explorer/blob/master/examples/button/ExplorerWithFlags.elm
