### ISSUE TITLE
Overflowed content is hidden/unreachable

### ISSUE THREAD

**Issue by derrickbeining** [kalutheo/elm-ui-explorer#86]
I'm finding that some content that overflows the viewport  on the Y axis is not visible. I can scroll most of the way, but not all the way. You can see an example of this happening on the design systems demo linked in the README: https://elm-ui-explorer.netlify.app/examples/dsm/#Styles/Typography/Typography. Scroll down to the bottom and you'll see some content cut off.

**Comment by kalutheo** [comment]
hello @derrickbeining thanks for the notice i will check that

**Comment by gpampara** [comment]
Also hitting this issue
